/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HP Simplified15.c                                     *
* Font:        HP Simplified                                         *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
*                                                                    *
**********************************************************************
*                                                                    *
* Pixel index of character 0x25 (37) at 5/12 set to 1                *
* Pixel index of character 0x25 (37) at 5/12 set to 0                *
* Pixel index of character 0x25 (37) at 1/2 set to 0                 *
* Pixel index of character 0x25 (37) at 2/1 set to 0                 *
* Pixel index of character 0x25 (37) at 1/3 set to 0                 *
* Pixel index of character 0x25 (37) at 1/4 set to 0                 *
* Pixel index of character 0x25 (37) at 1/5 set to 0                 *
* Pixel index of character 0x25 (37) at 1/6 set to 0                 *
* Pixel index of character 0x25 (37) at 3/7 set to 0                 *
* Pixel index of character 0x25 (37) at 4/7 set to 0                 *
* Pixel index of character 0x25 (37) at 2/7 set to 0                 *
* Pixel index of character 0x25 (37) at 2/6 set to 0                 *
* Pixel index of character 0x25 (37) at 5/6 set to 0                 *
* Pixel index of character 0x25 (37) at 5/5 set to 0                 *
* Pixel index of character 0x25 (37) at 5/2 set to 0                 *
* Pixel index of character 0x25 (37) at 4/1 set to 0                 *
* Pixel index of character 0x25 (37) at 5/3 set to 0                 *
* Pixel index of character 0x25 (37) at 5/4 set to 0                 *
* Pixel index of character 0x25 (37) at 4/2 set to 0                 *
* Pixel index of character 0x25 (37) at 3/1 set to 0                 *
* Pixel index of character 0x25 (37) at 4/2 set to 1                 *
* Pixel index of character 0x25 (37) at 2/2 set to 0                 *
* Pixel index of character 0x25 (37) at 3/2 set to 0                 *
* Pixel index of character 0x25 (37) at 4/2 set to 0                 *
* Pixel index of character 0x25 (37) at 4/3 set to 0                 *
* Pixel index of character 0x25 (37) at 4/4 set to 0                 *
* Pixel index of character 0x25 (37) at 4/5 set to 0                 *
* Pixel index of character 0x25 (37) at 4/6 set to 0                 *
* Pixel index of character 0x25 (37) at 3/6 set to 0                 *
* Pixel index of character 0x25 (37) at 2/5 set to 0                 *
* Pixel index of character 0x25 (37) at 2/3 set to 0                 *
* Pixel index of character 0x25 (37) at 2/4 set to 0                 *
* Pixel index of character 0x25 (37) at 6/5 set to 1                 *
* Pixel index of character 0x25 (37) at 6/4 set to 1                 *
* Pixel index of character 0x25 (37) at 6/3 set to 1                 *
* Pixel index of character 0x25 (37) at 5/2 set to 1                 *
* Pixel index of character 0x25 (37) at 4/2 set to 1                 *
* Pixel index of character 0x25 (37) at 3/3 set to 1                 *
* Pixel index of character 0x25 (37) at 3/4 set to 1                 *
* Pixel index of character 0x25 (37) at 3/5 set to 1                 *
* Pixel index of character 0x25 (37) at 4/7 set to 1                 *
* Pixel index of character 0x25 (37) at 5/7 set to 1                 *
* Pixel index of character 0x25 (37) at 6/6 set to 1                 *
* Pixel index of character 0x25 (37) at 3/6 set to 1                 *
* Pixel index of character 0x25 (37) at 10/13 set to 0               *
* Pixel index of character 0x25 (37) at 11/13 set to 0               *
* Pixel index of character 0x25 (37) at 11/13 set to 0               *
* Pixel index of character 0x25 (37) at 13/12 set to 0               *
* Pixel index of character 0x25 (37) at 13/12 set to 0               *
* Pixel index of character 0x25 (37) at 13/11 set to 0               *
* Pixel index of character 0x25 (37) at 13/9 set to 0                *
* Pixel index of character 0x25 (37) at 13/9 set to 0                *
* Pixel index of character 0x25 (37) at 13/8 set to 0                *
* Pixel index of character 0x25 (37) at 12/7 set to 0                *
* Pixel index of character 0x25 (37) at 12/8 set to 0                *
* Pixel index of character 0x25 (37) at 12/9 set to 0                *
* Pixel index of character 0x25 (37) at 13/10 set to 0               *
* Pixel index of character 0x25 (37) at 13/10 set to 0               *
* Pixel index of character 0x25 (37) at 12/10 set to 0               *
* Pixel index of character 0x25 (37) at 12/11 set to 0               *
* Pixel index of character 0x25 (37) at 12/12 set to 0               *
* Pixel index of character 0x25 (37) at 12/12 set to 0               *
* Pixel index of character 0x25 (37) at 12/13 set to 0               *
* Pixel index of character 0x25 (37) at 12/13 set to 0               *
* Pixel index of character 0x25 (37) at 12/13 set to 0               *
* Pixel index of character 0x25 (37) at 11/12 set to 0               *
* Pixel index of character 0x25 (37) at 11/12 set to 0               *
* Pixel index of character 0x25 (37) at 11/12 set to 0               *
* Pixel index of character 0x25 (37) at 11/9 set to 0                *
* Pixel index of character 0x25 (37) at 11/7 set to 0                *
* Pixel index of character 0x25 (37) at 11/8 set to 0                *
* Pixel index of character 0x25 (37) at 10/8 set to 0                *
* Pixel index of character 0x25 (37) at 10/9 set to 0                *
* Pixel index of character 0x25 (37) at 10/10 set to 0               *
* Pixel index of character 0x25 (37) at 10/11 set to 0               *
* Pixel index of character 0x25 (37) at 9/12 set to 0                *
* Pixel index of character 0x25 (37) at 11/12 set to 1               *
* Pixel index of character 0x25 (37) at 12/11 set to 1               *
* Pixel index of character 0x25 (37) at 12/10 set to 1               *
* Pixel index of character 0x25 (37) at 12/9 set to 1                *
* Pixel index of character 0x25 (37) at 12/8 set to 1                *
* Pixel index of character 0x25 (37) at 11/7 set to 1                *
* Pixel index of character 0x25 (37) at 10/8 set to 1                *
* Pixel index of character 0x25 (37) at 11/8 set to 1                *
* Pixel index of character 0x25 (37) at 11/11 set to 1               *
* Pixel index of character 0x25 (37) at 10/11 set to 1               *
* Pixel index of character 0x25 (37) at 4/6 set to 1                 *
* Pixel index of character 0x25 (37) at 5/6 set to 1                 *
* Pixel index of character 0x25 (37) at 5/3 set to 1                 *
* Pixel index of character 0x25 (37) at 4/3 set to 1                 *
* Edit/Shift/Left       at character 0x25 (37)                       *
* Edit/Shift/Left       at character 0x25 (37)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Edit/Shift/Right      at character 0x25 (37)                       *
* Edit/Shift/Left       at character 0x25 (37)                       *
* Edit/Shift/Left       at character 0x25 (37)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Pixel index of character 0x31 (49) at 1/3 set to 1                 *
* Pixel index of character 0x31 (49) at 1/2 set to 1                 *
* Pixel index of character 0x31 (49) at 1/2 set to 0                 *
* Pixel index of character 0x31 (49) at 1/4 set to 1                 *
* Pixel index of character 0x31 (49) at 2/4 set to 1                 *
* Pixel index of character 0x31 (49) at 3/4 set to 1                 *
* Pixel index of character 0x31 (49) at 2/2 set to 0                 *
* Pixel index of character 0x31 (49) at 3/4 set to 0                 *
* Pixel index of character 0x31 (49) at 2/4 set to 0                 *
* Pixel index of character 0x31 (49) at 1/4 set to 0                 *
* Pixel index of character 0x31 (49) at 1/3 set to 0                 *
* Pixel index of character 0x31 (49) at 3/1 set to 1                 *
* Pixel index of character 0x31 (49) at 2/2 set to 1                 *
* Pixel index of character 0x31 (49) at 1/3 set to 1                 *
* Pixel index of character 0x31 (49) at 1/4 set to 1                 *
* Pixel index of character 0x31 (49) at 2/4 set to 1                 *
* Pixel index of character 0x31 (49) at 1/3 set to 0                 *
* Pixel index of character 0x31 (49) at 1/3 set to 1                 *
* Pixel index of character 0x31 (49) at 3/3 set to 0                 *
* Pixel index of character 0x31 (49) at 3/3 set to 1                 *
* Pixel index of character 0x31 (49) at 3/1 set to 0                 *
* Pixel index of character 0x31 (49) at 1/3 set to 0                 *
* Pixel index of character 0x31 (49) at 1/4 set to 0                 *
* Pixel index of character 0x31 (49) at 2/4 set to 0                 *
* Pixel index of character 0x31 (49) at 1/3 set to 1                 *
* Pixel index of character 0x31 (49) at 1/4 set to 1                 *
* Pixel index of character 0x31 (49) at 2/4 set to 1                 *
* Pixel index of character 0x32 (50) at 1/1 set to 0                 *
* Pixel index of character 0x32 (50) at 1/2 set to 0                 *
* Pixel index of character 0x32 (50) at 1/2 set to 1                 *
* Pixel index of character 0x32 (50) at 1/3 set to 1                 *
* Pixel index of character 0x32 (50) at 2/3 set to 1                 *
* Pixel index of character 0x32 (50) at 7/11 set to 1                *
* Pixel index of character 0x32 (50) at 8/11 set to 1                *
* Pixel index of character 0x32 (50) at 8/13 set to 0                *
* Pixel index of character 0x33 (51) at 1/1 set to 0                 *
* Pixel index of character 0x33 (51) at 1/13 set to 0                *
* Pixel index of character 0x33 (51) at 1/3 set to 1                 *
* Pixel index of character 0x33 (51) at 1/11 set to 1                *
* Pixel index of character 0x33 (51) at 2/11 set to 1                *
* Pixel index of character 0x33 (51) at 2/3 set to 1                 *
* Pixel index of character 0x34 (52) at 5/5 set to 0                 *
* Pixel index of character 0x34 (52) at 5/6 set to 0                 *
* Pixel index of character 0x34 (52) at 5/7 set to 0                 *
* Pixel index of character 0x34 (52) at 5/8 set to 0                 *
* Pixel index of character 0x35 (53) at 8/1 set to 0                 *
* Pixel index of character 0x35 (53) at 1/1 set to 0                 *
* Pixel index of character 0x35 (53) at 7/3 set to 1                 *
* Pixel index of character 0x35 (53) at 8/3 set to 1                 *
* Pixel index of character 0x35 (53) at 7/3 set to 0                 *
* Pixel index of character 0x35 (53) at 8/3 set to 0                 *
* Pixel index of character 0x35 (53) at 8/1 set to 1                 *
* Pixel index of character 0x35 (53) at 1/13 set to 0                *
* Pixel index of character 0x35 (53) at 2/11 set to 1                *
* Pixel index of character 0x35 (53) at 1/11 set to 1                *
* Pixel index of character 0x35 (53) at 1/13 set to 1                *
* Pixel index of character 0x35 (53) at 2/11 set to 0                *
* Pixel index of character 0x35 (53) at 1/11 set to 0                *
* Pixel index of character 0x35 (53) at 1/1 set to 1                 *
* Pixel index of character 0x25 (37) at 1/7 set to 0                 *
* Pixel index of character 0x25 (37) at 2/7 set to 0                 *
* Pixel index of character 0x25 (37) at 3/6 set to 0                 *
* Pixel index of character 0x25 (37) at 0/2 set to 0                 *
* Pixel index of character 0x25 (37) at 1/1 set to 0                 *
* Pixel index of character 0x25 (37) at 3/2 set to 1                 *
* Pixel index of character 0x25 (37) at 2/1 set to 1                 *
* Pixel index of character 0x25 (37) at 1/1 set to 1                 *
* Pixel index of character 0x25 (37) at 2/3 set to 0                 *
* Pixel index of character 0x25 (37) at 1/3 set to 0                 *
* Pixel index of character 0x25 (37) at 0/2 set to 1                 *
* Pixel index of character 0x25 (37) at 0/6 set to 0                 *
* Pixel index of character 0x25 (37) at 3/2 set to 0                 *
* Pixel index of character 0x25 (37) at 0/2 set to 0                 *
* Pixel index of character 0x25 (37) at 1/2 set to 0                 *
* Pixel index of character 0x25 (37) at 2/2 set to 0                 *
* Pixel index of character 0x25 (37) at 3/2 set to 1                 *
* Pixel index of character 0x25 (37) at 0/2 set to 1                 *
* Pixel index of character 0x25 (37) at 7/13 set to 1                *
* Pixel index of character 0x25 (37) at 8/13 set to 1                *
* Pixel index of character 0x25 (37) at 7/11 set to 0                *
* Pixel index of character 0x25 (37) at 8/11 set to 0                *
* Pixel index of character 0x25 (37) at 7/7 set to 0                 *
* Pixel index of character 0x25 (37) at 8/7 set to 0                 *
* Pixel index of character 0x25 (37) at 6/8 set to 0                 *
* Pixel index of character 0x25 (37) at 9/8 set to 0                 *
* Pixel index of character 0x25 (37) at 6/12 set to 1                *
* Pixel index of character 0x25 (37) at 9/12 set to 1                *
* Pixel index of character 0x25 (37) at 7/12 set to 0                *
* Pixel index of character 0x25 (37) at 8/12 set to 0                *
* Pixel index of character 0x25 (37) at 9/1 set to 1                 *
* Pixel index of character 0x25 (37) at 0/13 set to 1                *
* Pixel index of character 0x25 (37) at 9/1 set to 0                 *
* Pixel index of character 0x25 (37) at 0/13 set to 0                *
* Pixel index of character 0x25 (37) at 1/1 set to 0                 *
* Pixel index of character 0x25 (37) at 2/1 set to 0                 *
* Pixel index of character 0x25 (37) at 0/2 set to 0                 *
* Pixel index of character 0x25 (37) at 3/2 set to 0                 *
* Pixel index of character 0x25 (37) at 1/2 set to 1                 *
* Pixel index of character 0x25 (37) at 2/2 set to 1                 *
* Pixel index of character 0x25 (37) at 7/13 set to 0                *
* Pixel index of character 0x25 (37) at 8/13 set to 0                *
* Pixel index of character 0x25 (37) at 6/12 set to 0                *
* Pixel index of character 0x25 (37) at 9/12 set to 0                *
* Pixel index of character 0x25 (37) at 7/12 set to 1                *
* Pixel index of character 0x25 (37) at 8/12 set to 1                *
*                                                                    *
**********************************************************************
  C-file modified by emWin Font Converter (ST) version 5.44: Nov 10 2023 at 13:39:27
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHPSimplified15;

/* SPACE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0020[ 15] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* EXCLAMATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0021[ 15] = { /* code 0021 */
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ________};

/* QUOTATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0022[ 15] = { /* code 0022 */
  ________,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* NUMBER SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0023[ 30] = { /* code 0023 */
  ________,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ___XX__X,X_______,
  __XXX_XX,________,
  __XX__XX,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  ________,________};

/* DOLLAR SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0024[ 30] = { /* code 0024 */
  ____XX__,________,
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  __XXXXXX,________,
  ___XXXXX,X_______,
  ___XX_XX,X_______,
  ___XX_XX,X_______,
  ___XX_XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  ___XX___,________};

/* PERCENT SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0025[ 30] = { /* code 0025 */
  ________,________,
  ________,________,
  _XX_____,X_______,
  X__X___X,X_______,
  X__X__XX,________,
  X__X_XX_,________,
  _XX__XX_,________,
  ____XX__,________,
  ___XX__X,X_______,
  ___XX_X_,_X______,
  __XX__X_,_X______,
  _XX___X_,_X______,
  _X_____X,X_______,
  ________,________,
  ________,________};

/* AMPERSAND */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0026[ 30] = { /* code 0026 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  __XXXXX_,_XX_____,
  _XXXXXXX,_XX_____,
  _XXX__XX,XXX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXXXXX,XXX_____,
  ___XXXXX,_XXX____,
  ________,________};

/* APOSTROPHE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0027[ 15] = { /* code 0027 */
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* LEFT PARENTHESIS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0028[ 15] = { /* code 0028 */
  ___XXX__,
  ___XX___,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  __XXX___,
  __XXX___,
  ___XX___};

/* RIGHT PARENTHESIS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0029[ 15] = { /* code 0029 */
  XXX_____,
  _XX_____,
  _XXX____,
  _XXX____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXX____,
  _XX_____};

/* ASTERISK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002A[ 15] = { /* code 002A */
  ________,
  ___XX___,
  _XXXX_X_,
  _XXXXXX_,
  ___XX___,
  __XXXX__,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* PLUS SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002B[ 30] = { /* code 002B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________};

/* COMMA */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002C[ 15] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XX_____};

/* HYPHEN-MINUS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002D[ 15] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

/* FULL STOP */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002E[ 15] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________};

/* SOLIDUS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_002F[ 15] = { /* code 002F */
  ____XXX_,
  ____XXX_,
  ___XXXX_,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXX____,
  XXX_____};

/* DIGIT ZERO */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0030[ 30] = { /* code 0030 */
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________};

/* DIGIT ONE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0031[ 30] = { /* code 0031 */
  ________,________,
  ____XXX_,________,
  __XXXXX_,________,
  _XXXXXX_,________,
  _XX_XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________};

/* DIGIT TWO */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0032[ 30] = { /* code 0032 */
  ________,________,
  __XXXXX_,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX___X,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ________,________};

/* DIGIT THREE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0033[ 30] = { /* code 0033 */
  ________,________,
  __XXXXX_,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _XX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ________,________};

/* DIGIT FOUR */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0034[ 30] = { /* code 0034 */
  ________,________,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XX__XX,________,
  __XX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________};

/* DIGIT FIVE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0035[ 30] = { /* code 0035 */
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  ________,________};

/* DIGIT SIX */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0036[ 30] = { /* code 0036 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________};

/* DIGIT SEVEN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0037[ 30] = { /* code 0037 */
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________};

/* DIGIT EIGHT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0038[ 30] = { /* code 0038 */
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________};

/* DIGIT NINE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0039[ 30] = { /* code 0039 */
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXX_XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,________,
  __XXXXXX,________,
  __XXXXX_,________,
  ________,________};

/* COLON */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003A[ 15] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________};

/* SEMICOLON */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003B[ 15] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XX_____};

/* LESS-THAN SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003C[ 30] = { /* code 003C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  ____XXXX,________,
  __XXXXX_,________,
  _XXXX___,________,
  _XXXX___,________,
  __XXXXXX,________,
  ____XXXX,________,
  _______X,________,
  ________,________,
  ________,________,
  ________,________};

/* EQUALS SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003D[ 30] = { /* code 003D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* GREATER-THAN SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003E[ 30] = { /* code 003E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,________,
  __XXXX__,________,
  __XXXXXX,________,
  _____XXX,X_______,
  _____XXX,X_______,
  __XXXXXX,________,
  __XXXX__,________,
  __XX____,________,
  ________,________,
  ________,________,
  ________,________};

/* QUESTION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_003F[ 15] = { /* code 003F */
  ________,
  _XXXXX__,
  _XXXXXX_,
  _XXXXXX_,
  ____XXX_,
  ____XXX_,
  ___XXXX_,
  __XXXX__,
  __XXX___,
  __XX____,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ________};

/* COMMERCIAL AT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0040[ 30] = { /* code 0040 */
  ________,________,
  _____XXX,XXX_____,
  ____XXXX,XXXX____,
  ___XXX__,__XXX___,
  __XX___X,XX_XX___,
  __XX__XX,XX__XX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX_XXX__,
  _XX__XXX,XXXXX___,
  _XX___XX,_XXX____,
  __XX____,________};

/* LATIN CAPITAL LETTER A */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0041[ 30] = { /* code 0041 */
  ________,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ________,________};

/* LATIN CAPITAL LETTER B */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0042[ 30] = { /* code 0042 */
  ________,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  ________,________};

/* LATIN CAPITAL LETTER C */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0043[ 30] = { /* code 0043 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  __XXX___,________,
  __XXXXXX,________,
  ___XXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER D */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0044[ 30] = { /* code 0044 */
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER E */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0045[ 30] = { /* code 0045 */
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER F */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0046[ 30] = { /* code 0046 */
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________};

/* LATIN CAPITAL LETTER G */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0047[ 30] = { /* code 0047 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,X_______,
  _XXX_XXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER H */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0048[ 30] = { /* code 0048 */
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________};

/* LATIN CAPITAL LETTER I */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0049[ 15] = { /* code 0049 */
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________};

/* LATIN CAPITAL LETTER J */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004A[ 15] = { /* code 004A */
  ________,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  XXXXX___,
  XXXX____,
  ________};

/* LATIN CAPITAL LETTER K */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004B[ 30] = { /* code 004B */
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  _XXX_XX_,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ________,________};

/* LATIN CAPITAL LETTER L */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004C[ 30] = { /* code 004C */
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER M */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004D[ 30] = { /* code 004D */
  ________,________,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXX_XXX,X_XXX___,
  _XXX_XXX,X_XXX___,
  _XXX_XXX,X_XXX___,
  _XXX__XX,__XXX___,
  _XXX__XX,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  ________,________};

/* LATIN CAPITAL LETTER N */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004E[ 30] = { /* code 004E */
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  _XXXX__X,XX______,
  _XXXXX_X,XX______,
  _XXXXX_X,XX______,
  _XXX_XXX,XX______,
  _XXX_XXX,XX______,
  _XXX__XX,XX______,
  _XXX__XX,XX______,
  _XXX__XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________};

/* LATIN CAPITAL LETTER O */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_004F[ 30] = { /* code 004F */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER P */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0050[ 30] = { /* code 0050 */
  ________,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________};

/* LATIN CAPITAL LETTER Q */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0051[ 30] = { /* code 0051 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ______XX,X_______};

/* LATIN CAPITAL LETTER R */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0052[ 30] = { /* code 0052 */
  ________,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________};

/* LATIN CAPITAL LETTER S */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0053[ 30] = { /* code 0053 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXX__,________,
  __XXXXX_,________,
  ____XXXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _XXXXXXX,________,
  _XXXXXX_,________,
  ________,________};

/* LATIN CAPITAL LETTER T */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0054[ 30] = { /* code 0054 */
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________};

/* LATIN CAPITAL LETTER U */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0055[ 30] = { /* code 0055 */
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________};

/* LATIN CAPITAL LETTER V */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0056[ 30] = { /* code 0056 */
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ________,________};

/* LATIN CAPITAL LETTER W */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0057[ 30] = { /* code 0057 */
  ________,________,
  _XXX____,___XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  __XX__XX,X__XXX__,
  __XX_XX_,XX_XX___,
  __XX_XX_,XX_XX___,
  __XXXXX_,XX_XX___,
  __XXXXX_,XXXXX___,
  __XXXXX_,XXXXX___,
  ___XXXX_,XXXXX___,
  ___XXX__,XXXX____,
  ___XXX__,_XXX____,
  ________,________};

/* LATIN CAPITAL LETTER X */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0058[ 30] = { /* code 0058 */
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XXXXXX,________,
  __XX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ________,________};

/* LATIN CAPITAL LETTER Y */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0059[ 30] = { /* code 0059 */
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________};

/* LATIN CAPITAL LETTER Z */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005A[ 30] = { /* code 005A */
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ________,________};

/* LEFT SQUARE BRACKET */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005B[ 15] = { /* code 005B */
  _XXXXX__,
  _XXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXXX__};

/* YEN SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005C[ 30] = { /* code 005C */
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ____XXX_,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ____XXX_,________,
  ____XXX_,________,
  ________,________};

/* RIGHT SQUARE BRACKET */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005D[ 15] = { /* code 005D */
  XXXXX___,
  XXXXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXX___};

/* CIRCUMFLEX ACCENT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005E[ 30] = { /* code 005E */
  ________,________,
  ___XXX__,________,
  __XXXXX_,________,
  __XXXXX_,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* LOW LINE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_005F[ 30] = { /* code 005F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* GRAVE ACCENT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0060[ 15] = { /* code 0060 */
  ________,
  _XXX____,
  __XX____,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* LATIN SMALL LETTER A */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0061[ 30] = { /* code 0061 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  __XXXXXX,________,
  _____XXX,________,
  __XXXXXX,________,
  _XXXXXXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXXXXXX,________,
  __XXXXXX,________,
  ________,________};

/* LATIN SMALL LETTER B */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0062[ 30] = { /* code 0062 */
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ________,________};

/* LATIN SMALL LETTER C */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0063[ 15] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XXXXX_,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  __XXXXX_,
  ___XXXX_,
  ________};

/* LATIN SMALL LETTER D */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0064[ 30] = { /* code 0064 */
  ________,________,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,X_______,
  ___XXX_X,X_______,
  ________,________};

/* LATIN SMALL LETTER E */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0065[ 30] = { /* code 0065 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  __XXXXXX,________,
  ___XXXXX,________,
  ________,________};

/* LATIN SMALL LETTER F */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0066[ 15] = { /* code 0066 */
  ________,
  ___XXXX_,
  __XXXXX_,
  __XXX___,
  _XXXXXX_,
  _XXXXXX_,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ________};

/* LATIN SMALL LETTER G */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0067[ 30] = { /* code 0067 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XX______,
  __XXXXXX,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,X_______,
  ___XX_XX,X_______,
  ______XX,X_______};

/* LATIN SMALL LETTER H */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0068[ 30] = { /* code 0068 */
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ________,________};

/* LATIN SMALL LETTER I */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0069[ 15] = { /* code 0069 */
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________};

/* LATIN SMALL LETTER J */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006A[ 15] = { /* code 006A */
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

/* LATIN SMALL LETTER K */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006B[ 30] = { /* code 006B */
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,X_______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  _XXX_XXX,________,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________};

/* LATIN SMALL LETTER L */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006C[ 15] = { /* code 006C */
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXX___,
  __XXX___,
  ________};

/* LATIN SMALL LETTER M */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006D[ 30] = { /* code 006D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,__XXX___,
  _XXXXXXX,XXXXXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  ________,________};

/* LATIN SMALL LETTER N */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006E[ 30] = { /* code 006E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ________,________};

/* LATIN SMALL LETTER O */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_006F[ 30] = { /* code 006F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________};

/* LATIN SMALL LETTER P */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0070[ 30] = { /* code 0070 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  _XXX____,________};

/* LATIN SMALL LETTER Q */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0071[ 30] = { /* code 0071 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XX______,
  __XXXXXX,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,X_______,
  ___XX_XX,X_______,
  ______XX,X_______};

/* LATIN SMALL LETTER R */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0072[ 15] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  _XX__XX_,
  _XXXXXX_,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________};

/* LATIN SMALL LETTER S */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0073[ 15] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XXXXXX_,
  _XXX____,
  _XXX____,
  _XXXXX__,
  __XXXXX_,
  ____XXX_,
  ____XXX_,
  _XXXXXX_,
  _XXXXX__,
  ________};

/* LATIN SMALL LETTER T */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0074[ 15] = { /* code 0074 */
  ________,
  ________,
  __XXX___,
  __XXX___,
  _XXXXXX_,
  _XXXXXX_,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXXXX_,
  ___XXXX_,
  ________};

/* LATIN SMALL LETTER U */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0075[ 30] = { /* code 0075 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXX__X,X_______,
  ________,________};

/* LATIN SMALL LETTER V */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0076[ 30] = { /* code 0076 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX__XX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XXXXX_,________,
  __XXXXX_,________,
  __XXXXX_,________,
  ________,________};

/* LATIN SMALL LETTER W */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0077[ 30] = { /* code 0077 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX____,__XXX___,
  _XXX__XX,__XXX___,
  _XXX__XX,__XXX___,
  _XXX__XX,__XXX___,
  __XX_XXX,X_XX____,
  __XX_XXX,X_XX____,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  ________,________};

/* LATIN SMALL LETTER X */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0078[ 30] = { /* code 0078 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  _XX___XX,X_______,
  _XXX_XXX,________,
  __XX_XXX,________,
  __XXXXX_,________,
  __XXXXX_,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ________,________};

/* LATIN SMALL LETTER Y */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_0079[ 30] = { /* code 0079 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX__XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________};

/* LATIN SMALL LETTER Z */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_007A[ 15] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _XXXXXX_,
  ____XXX_,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXXXXX_,
  _XXXXXX_,
  ________};

/* LEFT CURLY BRACKET */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_007B[ 15] = { /* code 007B */
  __XXXX__,
  _XXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXX_____,
  XXX_____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXXX__};

/* VERTICAL LINE */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_007C[ 15] = { /* code 007C */
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

/* RIGHT CURLY BRACKET */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_007D[ 15] = { /* code 007D */
  XXXX____,
  XXXXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXX___};

/* ACUTE ACCENT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_814C[ 15] = { /* code 814C */
  ________,
  ____XXX_,
  ___XXX__,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* DIAERESIS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_814E[ 15] = { /* code 814E */
  ________,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* REVERSE SOLIDUS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_815F[ 15] = { /* code 815F */
  XXX_____,
  XXX_____,
  _XX_____,
  _XXX____,
  _XXX____,
  _XXX____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ____XX__,
  ____XXX_};

/* HORIZONTAL ELLIPSIS */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8163[ 30] = { /* code 8163 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  ________,________};

/* LEFT SINGLE QUOTATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8165[ 15] = { /* code 8165 */
  ________,
  ___X____,
  __X_____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* RIGHT SINGLE QUOTATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8166[ 15] = { /* code 8166 */
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  __X_____,
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* LEFT DOUBLE QUOTATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8167[ 15] = { /* code 8167 */
  ________,
  ___X___X,
  __X___X_,
  _XXX_XXX,
  _XXX_XXX,
  _XXX_XXX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* RIGHT DOUBLE QUOTATION MARK */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8168[ 15] = { /* code 8168 */
  ________,
  _XXX_XXX,
  _XXX_XXX,
  _XXX_XXX,
  __X___X_,
  _X___X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* MINUS SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_817C[ 30] = { /* code 817C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* PLUS-MINUS SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_817D[ 30] = { /* code 817D */
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ________,________};

/* MULTIPLICATION SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_817E[ 30] = { /* code 817E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___XX,________,
  _XXX_XXX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXXX_XX,X_______,
  __XX___X,________,
  ________,________,
  ________,________,
  ________,________};

/* DIVISION SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8180[ 30] = { /* code 8180 */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________};

/* NOT EQUAL TO */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8182[ 30] = { /* code 8182 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  ______XX,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ____XX__,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ___X____,________,
  __XX____,________,
  ________,________,
  ________,________};

/* INFINITY */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8187[ 30] = { /* code 8187 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXX_XX,X_______,
  _XXXXXXX,XX______,
  _XX_XXX_,XX______,
  _XX_XXX_,XX______,
  _XXXXXXX,XX______,
  __XXX_XX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* DEGREE SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_818B[ 15] = { /* code 818B */
  ________,
  _XXX____,
  XXXXX___,
  XX_XX___,
  XXXXX___,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* CENT SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8191[ 30] = { /* code 8191 */
  ________,________,
  ______XX,________,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX_XX_,________,
  _XXX_XX_,________,
  _XXX_XX_,________,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  _____XX_,________,
  _____XX_,________,
  ________,________};

/* POUND SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8192[ 30] = { /* code 8192 */
  ________,________,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________};

/* SECTION SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_8198[ 30] = { /* code 8198 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XXX___,________,
  __XXXXX_,________,
  __XXXXXX,________,
  _XXX_XXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXX_XX,X_______,
  __XXXXXX,________,
  ___XXXXX,________,
  ______XX,X_______,
  ______XX,X_______,
  __XXXXXX,X_______};

/* NOT SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81CA[ 30] = { /* code 81CA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* PARTIAL DIFFERENTIAL */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81DD[ 30] = { /* code 81DD */
  ________,________,
  __XXXXX_,________,
  __XXXXXX,________,
  _____XXX,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________};

/* SQUARE ROOT */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81E3[ 30] = { /* code 81E3 */
  ________,XX______,
  ________,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  __XX__XX,X_______,
  XXXX__XX,X_______,
  XXXXX_XX,X_______,
  __XXX_XX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________};

/* INTEGRAL */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81E7[ 15] = { /* code 81E7 */
  ________,
  ___XXX__,
  __XXXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__};

/* PER MILLE SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81F1[ 45] = { /* code 81F1 */
  ________,________,________,
  __XXX___,___XX___,________,
  _XXXXX__,__XX____,________,
  _XX_XX__,__XX____,________,
  _XX_XX__,_XX_____,________,
  _XX_XX__,XX______,________,
  _XXXXX__,XX______,________,
  __XXX__X,X_XXX___,_XXX____,
  ______XX,_XXXXX__,XXXXX___,
  ______XX,_XX_XX__,XX_XX___,
  _____XX_,_XX_XX__,XX_XX___,
  ____XX__,_XX_XX__,XX_XX___,
  ____XX__,_XXXXX__,XXXXX___,
  ___XX___,__XXX___,_XXX____,
  ________,________,________};

/* DAGGER */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81F5[ 30] = { /* code 81F5 */
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

/* DOUBLE DAGGER */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81F6[ 30] = { /* code 81F6 */
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ___XXX__,________,
  ___XXX__,________};

/* PILCROW SIGN */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_81F7[ 30] = { /* code 81F7 */
  ________,________,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXX__,XX______,
  _XXXXX__,XX______,
  _XXXXX__,XX______,
  _XXXXX__,XX______,
  _XXXXX__,XX______,
  __XXXX__,XX______,
  ___XXX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______};

/* GREEK CAPITAL LETTER DELTA */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_83A2[ 30] = { /* code 83A2 */
  ________,________,
  __XXXXX_,________,
  __XXXXX_,________,
  __XX_XX_,________,
  __XX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ________,________};

/* GREEK CAPITAL LETTER OMEGA */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_83B6[ 30] = { /* code 83B6 */
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  _XXXX_XX,XX______,
  _XXXX_XX,XX______,
  ________,________};

/* GREEK SMALL LETTER MU */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_83CA[ 30] = { /* code 83CA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  _XXXX__X,X_______,
  _XXX____,________};

/* GREEK SMALL LETTER PI */
GUI_CONST_STORAGE unsigned char acGUI_FontHPSimplified15_83CE[ 30] = { /* code 83CE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHPSimplified15_CharInfo[124] = {
   {   3,   3,  1, acGUI_FontHPSimplified15_0020 } /* code 0020 */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_0022 } /* code 0022 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_0023 } /* code 0023 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0024 } /* code 0024 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0025 } /* code 0025 */
  ,{  12,  12,  2, acGUI_FontHPSimplified15_0026 } /* code 0026 */
  ,{   4,   4,  1, acGUI_FontHPSimplified15_0027 } /* code 0027 */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_0028 } /* code 0028 */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_002A } /* code 002A */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_002B } /* code 002B */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_002C } /* code 002C */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_002D } /* code 002D */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_002E } /* code 002E */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_002F } /* code 002F */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0030 } /* code 0030 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0031 } /* code 0031 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0032 } /* code 0032 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0033 } /* code 0033 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0034 } /* code 0034 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0035 } /* code 0035 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0036 } /* code 0036 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0037 } /* code 0037 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0038 } /* code 0038 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0039 } /* code 0039 */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_003A } /* code 003A */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_003B } /* code 003B */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_003C } /* code 003C */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_003D } /* code 003D */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_003F } /* code 003F */
  ,{  15,  15,  2, acGUI_FontHPSimplified15_0040 } /* code 0040 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0041 } /* code 0041 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0042 } /* code 0042 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0043 } /* code 0043 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_0044 } /* code 0044 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0045 } /* code 0045 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0046 } /* code 0046 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0047 } /* code 0047 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_0048 } /* code 0048 */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_0049 } /* code 0049 */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_004A } /* code 004A */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_004B } /* code 004B */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_004C } /* code 004C */
  ,{  14,  14,  2, acGUI_FontHPSimplified15_004D } /* code 004D */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_004E } /* code 004E */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_004F } /* code 004F */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0050 } /* code 0050 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_0051 } /* code 0051 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0052 } /* code 0052 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0053 } /* code 0053 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0054 } /* code 0054 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_0055 } /* code 0055 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0056 } /* code 0056 */
  ,{  15,  15,  2, acGUI_FontHPSimplified15_0057 } /* code 0057 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0058 } /* code 0058 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0059 } /* code 0059 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_005A } /* code 005A */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_005B } /* code 005B */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_005C } /* code 005C */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_005D } /* code 005D */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_005E } /* code 005E */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_0060 } /* code 0060 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0061 } /* code 0061 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_0063 } /* code 0063 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0064 } /* code 0064 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0065 } /* code 0065 */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_0066 } /* code 0066 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0067 } /* code 0067 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0068 } /* code 0068 */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_0069 } /* code 0069 */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_006A } /* code 006A */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_006B } /* code 006B */
  ,{   5,   5,  1, acGUI_FontHPSimplified15_006C } /* code 006C */
  ,{  15,  15,  2, acGUI_FontHPSimplified15_006D } /* code 006D */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_006E } /* code 006E */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_006F } /* code 006F */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0070 } /* code 0070 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0071 } /* code 0071 */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_0073 } /* code 0073 */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_0074 } /* code 0074 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_0075 } /* code 0075 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0076 } /* code 0076 */
  ,{  14,  14,  2, acGUI_FontHPSimplified15_0077 } /* code 0077 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0078 } /* code 0078 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_007A } /* code 007A */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_007B } /* code 007B */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_007C } /* code 007C */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_814C } /* code 814C */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_814E } /* code 814E */
  ,{   7,   7,  1, acGUI_FontHPSimplified15_815F } /* code 815F */
  ,{  16,  16,  2, acGUI_FontHPSimplified15_8163 } /* code 8163 */
  ,{   4,   4,  1, acGUI_FontHPSimplified15_8165 } /* code 8165 */
  ,{   4,   4,  1, acGUI_FontHPSimplified15_8166 } /* code 8166 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_8167 } /* code 8167 */
  ,{   8,   8,  1, acGUI_FontHPSimplified15_8168 } /* code 8168 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_817C } /* code 817C */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_817D } /* code 817D */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_817E } /* code 817E */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_8180 } /* code 8180 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_8182 } /* code 8182 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_8187 } /* code 8187 */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_818B } /* code 818B */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_8191 } /* code 8191 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_8192 } /* code 8192 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_8198 } /* code 8198 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_81CA } /* code 81CA */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_81DD } /* code 81DD */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_81E3 } /* code 81E3 */
  ,{   6,   6,  1, acGUI_FontHPSimplified15_81E7 } /* code 81E7 */
  ,{  21,  21,  3, acGUI_FontHPSimplified15_81F1 } /* code 81F1 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_81F5 } /* code 81F5 */
  ,{   9,   9,  2, acGUI_FontHPSimplified15_81F6 } /* code 81F6 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_81F7 } /* code 81F7 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_83A2 } /* code 83A2 */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_83B6 } /* code 83B6 */
  ,{  10,  10,  2, acGUI_FontHPSimplified15_83CA } /* code 83CA */
  ,{  11,  11,  2, acGUI_FontHPSimplified15_83CE } /* code 83CE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop23 = {
   0x83CE /* first character */
  ,0x83CE /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[123] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop22 = {
   0x83CA /* first character */
  ,0x83CA /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[122] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop21 = {
   0x83B6 /* first character */
  ,0x83B6 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[121] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop20 = {
   0x83A2 /* first character */
  ,0x83A2 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[120] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop19 = {
   0x81F5 /* first character */
  ,0x81F7 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[117] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop18 = {
   0x81F1 /* first character */
  ,0x81F1 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[116] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop17 = {
   0x81E7 /* first character */
  ,0x81E7 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[115] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop16 = {
   0x81E3 /* first character */
  ,0x81E3 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[114] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop15 = {
   0x81DD /* first character */
  ,0x81DD /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[113] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop14 = {
   0x81CA /* first character */
  ,0x81CA /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[112] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop13 = {
   0x8198 /* first character */
  ,0x8198 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[111] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop12 = {
   0x8191 /* first character */
  ,0x8192 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[109] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop11 = {
   0x818B /* first character */
  ,0x818B /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[108] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop10 = {
   0x8187 /* first character */
  ,0x8187 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[107] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop9 = {
   0x8182 /* first character */
  ,0x8182 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[106] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop8 = {
   0x8180 /* first character */
  ,0x8180 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[105] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop7 = {
   0x817C /* first character */
  ,0x817E /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[102] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop6 = {
   0x8165 /* first character */
  ,0x8168 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[ 98] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop5 = {
   0x8163 /* first character */
  ,0x8163 /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[ 97] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop4 = {
   0x815F /* first character */
  ,0x815F /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[ 96] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop3 = {
   0x814E /* first character */
  ,0x814E /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[ 95] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop2 = {
   0x814C /* first character */
  ,0x814C /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[ 94] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHPSimplified15_Prop1 = {
   0x0020 /* first character */
  ,0x007D /* last character  */
  ,&GUI_FontHPSimplified15_CharInfo[  0] /* address of first character */
  ,&GUI_FontHPSimplified15_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHPSimplified15 = {
   GUI_FONTTYPE_PROP_SJIS /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHPSimplified15_Prop1}
  ,14 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

